"""user_film

Revision ID: 1dce7f409a31
Revises: 7dc385ef2e02
Create Date: 2022-08-13 20:42:12.341587

"""
import uuid
from datetime import datetime


from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1dce7f409a31"
down_revision = "7dc385ef2e02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_film",
        sa.Column("created_at", sa.DateTime(timezone=False), default=sa.sql.func.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=False),
            default=sa.sql.func.now(),
            onupdate=datetime.utcnow,
        ),
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4
        ),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("film_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("watched", sa.Boolean(), default=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "film_id", name="_user_film"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_film", schema="content")
    # ### end Alembic commands ###
