"""receipt_item_type

Revision ID: 77f5794a1db2
Revises: 1dce7f409a31
Create Date: 2022-08-14 22:56:08.728487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f5794a1db2'
down_revision = '1dce7f409a31'
branch_labels = None
depends_on = None

receipt_item_type_enum = sa.Enum('FILM', 'SUBSCRIPTION', name='receiptitemtypeenum')


def upgrade() -> None:
    receipt_item_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('type', receipt_item_type_enum, nullable=False), schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'type', schema='content')
    # ### end Alembic commands ###

    receipt_item_type_enum.drop(op.get_bind())
