"""added_transaction_id
 Revision ID: 94f21b034c8b
 Revises: bb8716cbc5fd
 Create Date: 2022-08-22 12:28:52.053120
 """
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "94f21b034c8b"
down_revision = "bb8716cbc5fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_films",
        sa.Column("transaction_id", postgresql.UUID(as_uuid=True), nullable=True),
        schema="content",
    )
    op.create_foreign_key(
        None,
        "users_films",
        "transactions",
        ["transaction_id"],
        ["id"],
        source_schema="content",
        referent_schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_films", schema="content", type_="foreignkey")
    op.drop_column("users_films", "transaction_id", schema="content")
    # ### end Alembic commands ###
