"""user_film_add_price

Revision ID: c2b3f756e7a7
Revises: 22484df4de31
Create Date: 2022-08-13 11:00:59.734219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2b3f756e7a7'
down_revision = '22484df4de31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_film', sa.Column('price', sa.Float(), nullable=False), schema='content')
    op.alter_column('user_film', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='content')
    op.alter_column('user_film', 'film_id',
               existing_type=postgresql.UUID(),
               nullable=False,
               schema='content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_film', 'film_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='content')
    op.alter_column('user_film', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True,
               schema='content')
    op.drop_column('user_film', 'price', schema='content')
    # ### end Alembic commands ###
