"""products

Revision ID: d057d267953f
Revises: 7dc385ef2e02
Create Date: 2022-08-09 23:30:42.345814

"""
import uuid
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d057d267953f"
down_revision = "7dc385ef2e02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("created_at", sa.DateTime(timezone=False), default=sa.sql.func.now()),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=False),
            default=sa.sql.func.now(),
            onupdate=datetime.utcnow,
        ),
        sa.Column(
            "id", postgresql.UUID(as_uuid=True), nullable=False, default=uuid.uuid4
        ),
        sa.Column("name", sa.String(length=1024), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="content",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products", schema="content")
    # ### end Alembic commands ###
